app_settings:
  app_type: "connector" # only lowercase letters, numbers, and underscores are allowed, e.g. salesforce, sap, zoho_crm, etc.
  app_name: "Shopify Connector App"
  app_icon_svg_url: "https://www.svgrepo.com/show/303503/shopify-logo.svg" # this is the icon of the app, should be a URL pointing to a SVG file.
  app_description: "App to fetch Shopify data"
  routes_directory: "src/modules" # this is the directory where the modules are located.

local_development_settings:
  sentry_dsn: ""
  cors_origins: ["*"]
  routes_directory: "src/modules"
  debug: true
  host: "0.0.0.0"
  port: 2003
